### ISSUE TITLE
Email should be checked

### ISSUE THREAD

**Issue by ganeshhubale** [paint-it/genpass#45]
- Before adding email to database. We must have to check if given email address is correct.

**Comment by Yadnyawalkya** [comment]
Validation is always a good idea but not in this case. Here we must consider the fact that users not going to use only "email addresses" for websites. Users should have the freedom to choose what he/she wants to add as a userid, it could be username/mobile number/PAN (not kidding! income tax website does that). So, I feel its OKAY to skip validations here. (Reminds me -- https://www.youtube.com/watch?v=WdYDUuvROEU)

Need opinion.

cc @mayurilahane @ganeshhubale

**Comment by mayurilahane** [comment]
I just saw some random website didn't use even any of this info. like,
- https://www.lastpass.com/password-generator
- https://passwordsgenerator.net/
so, I think it can be optional what do you think 
@ganeshhubale @Yadnyawalkya
