### ISSUE TITLE
Create database connectivity 

### ISSUE THREAD

**Issue by mayurilahane** [paint-it/genpass#8]
Use sqllite3 database.
create table :
table_name - manage_passwords
- id
- Name
- Url
- Email
- Tag
- Creation date
- Notes
- Level(strong, low,medium)
- importance(Stared/Unstarred).
- Last modified.

Database actions:
- Add.
- Edit.
- Delete.
- Show.
- Search via email tag attributes.

- Clipboard(this is not a database action)

code should be in database.py

- Partially fixed https://github.com/paint-it/genpass/pull/9

**Comment by ganeshhubale** [comment]
Need PR for adding entries of **creation date**,  **email** and **portal url** in DB
Fixed in https://github.com/paint-it/genpass/pull/40
